### ISSUE TITLE
CKAN - Could not load view: DataProxy returned an error

### ISSUE THREAD

**Issue by davidloz86** [okfn/docker-ckan#85]
Hi,

I would like to see CSV visualization on CKAN, but only appear the next following message error: Could not load view: DataProxy returned an error.

I replicated this steps:
- Clone (https://github.com/okfn/docker-ckan) into a directory of my choice: 
- Copy the included .env.example and rename it to .env to modify:
      - I used the default values on the .env.example file will get you a working CKAN instance. 
      - I changed CKAN_SITE_URL=http://ckan:5000 by CKAN_SITE_URL=http://localhost:5000
- Then I Built the images and started the containers

After that, when I log in as ckan-admin in http://localhost:5000/, if I add a organization and create a CVS dataset and I preview it don't appear nothing, only the message error.

Could you help me?

Thanks,
David

**Comment by mikelhpdatke** [comment]
This is the datapusher's error. You could try keitaro instead. For example:
```

  datapusher:
    container_name: datapusher
    image: keitaro/ckan-datapusher:latest

    ports:
      - "8000:8000"
    environment:
      - DATAPUSHER_MAX_CONTENT_LENGTH=${DATAPUSHER_MAX_CONTENT_LENGTH}
      - DATAPUSHER_CHUNK_SIZE=${DATAPUSHER_CHUNK_SIZE}
      - DATAPUSHER_CHUNK_INSERT_ROWS=${DATAPUSHER_CHUNK_INSERT_ROWS}
      - DATAPUSHER_DOWNLOAD_TIMEOUT=${DATAPUSHER_DOWNLOAD_TIMEOUT}
      - DATAPUSHER_SSL_VERIFY=${DATA_PUSHER_SSL_VERIFY}
      - DATAPUSHER_REWRITE_RESOURCES=${DATAPUSHER_REWRITE_RESOURCES}
      - DATAPUSHER_REWRITE_URL=${DATAPUSHER_REWRITE_URL}
```
